### ISSUE TITLE
NuGet package DLL

### ISSUE THREAD

**Issue by nemec** [AfterShip/aftership-net#2]
Hi, I'm trying to use this library in an ASP.Net 5 project but I'm having a couple of issues.

I noticed that your NuGet package consists of an EXE file, which I've discovered is [not supported](http://stackoverflow.com/questions/28936000/namespace-from-nuget-package-reference-canot-be-found-in-controller/) by the new framework -- only DLLs can be referenced as dependencies. It looks like your Test class holds the Main method but it should really be excluded from the final package (along with the NUnit tests, if you compiled them in too).

Would it be possible to create a new NuGet package with the source built as a DLL?

**Comment by jvb93** [comment]
This is still an issue. NuGet will NOT work if using this as a dependency. Had to remove the main function from the tests.cs and set the output type to class library versus console application. This makes it build to a dll (as an SDK should) versus an exe. Very inconvenient.
