### ISSUE TITLE
System.Web Dependency

### ISSUE THREAD

**Issue by nemec** [AfterShip/aftership-net#3]
Related to my efforts in #2 to build this on ASP.Net 5, the new framework doesn't have System.Web included so I needed to find an alternate solution.

I found [this SO post](http://stackoverflow.com/a/7878050/564755) that says to use `System.Uri.EscapeDataString` instead of [HttpUtility.UrlEncode](https://github.com/AfterShip/aftership-net/blob/69844a7950e984403a643fd22dcf0348e69b97f8/QueryString.cs#L37) and it seems to work fine for encoding query string parameters. Is it possible to include this in the official NuGet package to reduce dependencies? I could submit a pull request if necessary.

**Comment by jesus-** [comment]
Hi,
Sure, make a PR and we will do some testing.

**Comment by jesus-** [comment]
Hello @nemec,

We had to update the .NET SDK, so I had the opportunity to made the changes you specified (Aftership version 4.0.11). Thank you very much for you suggestion, if you have any other let us know.
